
export const DataBase = [
    {
      id:1,title:"حقيبة مدرسية زرقاء",price:1050.00,PriceCuts:200.95,
      description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",category:"",
      image:"https://i.pinimg.com/originals/d2/dc/86/d2dc86ee8596f71e9ea3ada5cdeffa78.jpg",
      image2:"https://ctl.s6img.com/society6/img/unkUxcurymDaTkQwRdlS-MJr440/w_1500/backpacks/standard/front/~artwork,fw_3900,fh_4575,fx_-338,iw_4575,ih_4575/s6-original-art-uploads/society6/uploads/misc/b933d2a0c7d74d9b967731ab8d797caf/~~/coral-color-air-plant-white-background-decor-society6-buyart-backpacks.jpg",
      image3:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVHTo25GHz1t6rEAv1bWSIpXbops8Ygg0rlw&usqp=CAU",
      image4:"https://thumbs.dreamstime.com/b/top-view-red-school-backpack-white-background-156039101.jpg",
      commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
      commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
      commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:2,title:"حقيبة أعمال,قديمة الطراز",price:850.00,PriceCuts:1500.95,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",
        category:"أدوات مدرسية",
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1579900877-41aU141yrML.jpg",
        image2:"https://neimanmarcus.scene7.com/is/image/NeimanMarcus/NMN3GCD_20_m?&wid=456&height=570",
        image3:"https://cdn.lookastic.com/brown-leather-backpack/ledge-leather-backpack-61941-original.jpg",
        image4:"https://images.neimanmarcus.com/ca/11/product_assets/N/3/G/C/D/NMN3GCD_au.jpg",
        commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
        commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
        commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      
      },
      {
        id:3,title:"أيفون إكس",price:1050.00,PriceCuts:2000.95,
            description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",
            category:"هاتف محمول",
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR58UTZTqsgPz2hT0eWen6w7K85Ilc0ZvwJRQ&usqp=CAU",
            image2:"https://www.ifixegy.com/wp-content/uploads/2019/10/iphonex-TA.jpg",
            image3:"https://9to5mac.com/wp-content/uploads/sites/6/2018/05/mi-8-iphone-x-comparison.jpg?quality=82&strip=all",
            image4:"https://thumbs.dreamstime.com/b/varna-bulgaria-january-perspective-view-new-apple-iphone-isolated-white-background-new-ios-homescreen-iphone-frameless-109022870.jpg",
            commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
            commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
            commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:4,title:"تيشرت أزرق",price:150,PriceCuts:200,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",category:"ملابس رجال",
        image:"https://cdn.shopify.com/s/files/1/0012/9892/3622/products/3003103_002_1_0_390e8693-e6d4-4abe-8936-58d8dc3aa630_1200x.jpg?v=1581463570",
        image2:"https://cdn.shopify.com/s/files/1/0012/9892/3622/products/3003103_002_2_0_81d12a93-0be2-42e1-b8c1-72d4e6211b45_1200x.jpg?v=1581463570",
        image3:"https://cdn.blankstyle.com/files/imagecache/product_full/18181_f_fl_1553910627.jpg",
        image4:"https://cdn.shopify.com/s/files/1/0012/9892/3622/products/3008128-002-Breeze_T-Shirt_II-Black_190528_1224.jpg?v=1576103557",
        commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
        commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
        commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:5,title:"جهاز تحكم بلاي ستيشن 4",price:400.00,PriceCuts:750.95,
            description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",category:"",
            image:"https://m.media-amazon.com/images/I/71nbTZzSreS._AC_SS450_.jpg",
            image2:"https://m.media-amazon.com/images/I/71D1eYAvv+S._AC_SS450_.jpg",
            image3:"https://i5.walmartimages.com/asr/efd870af-f44d-46b4-8437-a8f50ce3937d.514d418a0578f87895835658feaa3622.jpeg",
            image4:"https://m.media-amazon.com/images/I/71klbMJTPKS._AC_SX450_.jpg",
            commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
            commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
            commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        
        id:6,title:"كراريس للملاحظات",price:650.00,PriceCuts:1000.95,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",category:"أدوات مدرسية",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbltVFeZdwBeGcNu4QR58C8iBLexHOoXCGyo358RT6NVzzhcxzSmGLnRIMqa3Kj6ZdNBA&usqp=CAU",
        image2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRwSeVsKF_XajJ0-qNvyE_yqaiteQZr87hXwIbU1DOu_eGDY_nXPYm5rmHfxb5caWuTEM&usqp=CAU",
        image3:"https://previews.123rf.com/images/atlasfoto/atlasfoto1906/atlasfoto190600730/124745713-color-notebooks-with-space-for-text-isolated-on-white-background.jpg",
        image4:"https://s3.envato.com/files/252563341/educcolour-6.jpg",
        commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
        commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
        commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:7,title:"جهاز تحكم بلاي ستيشن 4",price:400.00,PriceCuts:750.95,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",category:"",
            image:"https://m.media-amazon.com/images/I/71nbTZzSreS._AC_SS450_.jpg",
            image2:"https://m.media-amazon.com/images/I/71D1eYAvv+S._AC_SS450_.jpg",
            image3:"https://i5.walmartimages.com/asr/efd870af-f44d-46b4-8437-a8f50ce3937d.514d418a0578f87895835658feaa3622.jpeg",
            image4:"https://m.media-amazon.com/images/I/71klbMJTPKS._AC_SX450_.jpg",
            commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
            commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
            commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:8,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",
            category:"هاتف محمول",
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR58UTZTqsgPz2hT0eWen6w7K85Ilc0ZvwJRQ&usqp=CAU",
            image2:"https://www.ifixegy.com/wp-content/uploads/2019/10/iphonex-TA.jpg",
            image3:"https://9to5mac.com/wp-content/uploads/sites/6/2018/05/mi-8-iphone-x-comparison.jpg?quality=82&strip=all",
            image4:"https://thumbs.dreamstime.com/b/varna-bulgaria-january-perspective-view-new-apple-iphone-isolated-white-background-new-ios-homescreen-iphone-frameless-109022870.jpg",
            commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
            commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
            commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:9,
        id:2,title:"حقيبة أعمال,قديمة الطراز",price:850.00,PriceCuts:1500.95,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",
        category:"أدوات مدرسية",
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1579900877-41aU141yrML.jpg",
        image2:"https://neimanmarcus.scene7.com/is/image/NeimanMarcus/NMN3GCD_20_m?&wid=456&height=570",
        image3:"https://cdn.lookastic.com/brown-leather-backpack/ledge-leather-backpack-61941-original.jpg",
        image4:"https://images.neimanmarcus.com/ca/11/product_assets/N/3/G/C/D/NMN3GCD_au.jpg",
        commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
        commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
        commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      },
      {
        id:10,
        title:"هجوم العمالقة حقيبة مدرسية",
        price:109.95,
        description:"لحقيبة المدرسية أو حقيبة الكتب أو الحقيبة الدراسية أو قِمَطْر هي الوسيلة التي يحفظ بها التلاميذ كتبهم وحاجات أخرى (الأدوات المدرسية) عند تنقلهم في الـمدرسة، وحجم المحفظة عادة يكون بحجم أكثر من الكتب، غالبًا ما تصنع من الجلد، وقد يكون جلدًا طبيعيًا غالي الثمن أو من الجلد الصناعي الرخيص، أو من النايلون أو القماش، أو من",
        category:"أدوات مدرسية",
        image1:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        image2:"https://thumbs.dreamstime.com/b/school-backpack-white-background-151312141.jpg",
        image3:"https://st4.depositphotos.com/10614052/22984/i/1600/depositphotos_229843646-stock-photo-school-backpack-white-background.jpg",
        PriceCuts:200.95,
        testimonialsPrictures:"https://goorelax.shop/wp-content/uploads/2021/06/2-1.jpg",
      },
      {
        id:11,
        title:"هجوم العمالقة حقيبة مدرسية",
        price:109.95,
        description:"لحقيبة المدرسية أو حقيبة الكتب أو الحقيبة الدراسية أو قِمَطْر هي الوسيلة التي يحفظ بها التلاميذ كتبهم وحاجات أخرى (الأدوات المدرسية) عند تنقلهم في الـمدرسة، وحجم المحفظة عادة يكون بحجم أكثر من الكتب، غالبًا ما تصنع من الجلد، وقد يكون جلدًا طبيعيًا غالي الثمن أو من الجلد الصناعي الرخيص، أو من النايلون أو القماش، أو من",
        category:"أدوات مدرسية",
        image1:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        image2:"https://thumbs.dreamstime.com/b/school-backpack-white-background-151312141.jpg",
        image3:"https://st4.depositphotos.com/10614052/22984/i/1600/depositphotos_229843646-stock-photo-school-backpack-white-background.jpg",
        PriceCuts:200.95,
        testimonialsPrictures:"https://goorelax.shop/wp-content/uploads/2021/06/2-1.jpg",
      },
      {
        id:12,
        title:"هجوم العمالقة حقيبة مدرسية",
        price:109.95,
        description:"لحقيبة المدرسية أو حقيبة الكتب أو الحقيبة الدراسية أو قِمَطْر هي الوسيلة التي يحفظ بها التلاميذ كتبهم وحاجات أخرى (الأدوات المدرسية) عند تنقلهم في الـمدرسة، وحجم المحفظة عادة يكون بحجم أكثر من الكتب، غالبًا ما تصنع من الجلد، وقد يكون جلدًا طبيعيًا غالي الثمن أو من الجلد الصناعي الرخيص، أو من النايلون أو القماش، أو من",
        category:"أدوات مدرسية",
        image1:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        image2:"https://thumbs.dreamstime.com/b/school-backpack-white-background-151312141.jpg",
        image3:"https://st4.depositphotos.com/10614052/22984/i/1600/depositphotos_229843646-stock-photo-school-backpack-white-background.jpg",
        PriceCuts:200.95,
        testimonialsPrictures:"https://goorelax.shop/wp-content/uploads/2021/06/2-1.jpg",
      },
      {
        id:13,
        title:"هجوم العمالقة حقيبة مدرسية",
        price:109.95,
        description:"لحقيبة المدرسية أو حقيبة الكتب أو الحقيبة الدراسية أو قِمَطْر هي الوسيلة التي يحفظ بها التلاميذ كتبهم وحاجات أخرى (الأدوات المدرسية) عند تنقلهم في الـمدرسة، وحجم المحفظة عادة يكون بحجم أكثر من الكتب، غالبًا ما تصنع من الجلد، وقد يكون جلدًا طبيعيًا غالي الثمن أو من الجلد الصناعي الرخيص، أو من النايلون أو القماش، أو من",
        category:"أدوات مدرسية",
        image1:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        image2:"https://thumbs.dreamstime.com/b/school-backpack-white-background-151312141.jpg",
        image3:"https://st4.depositphotos.com/10614052/22984/i/1600/depositphotos_229843646-stock-photo-school-backpack-white-background.jpg",
        PriceCuts:200.95,
        testimonialsPrictures:"https://goorelax.shop/wp-content/uploads/2021/06/2-1.jpg",
      },
      {
        id:14,
        title:"هجوم العمالقة حقيبة مدرسية",
        price:109.95,
        description:"لحقيبة المدرسية أو حقيبة الكتب أو الحقيبة الدراسية أو قِمَطْر هي الوسيلة التي يحفظ بها التلاميذ كتبهم وحاجات أخرى (الأدوات المدرسية) عند تنقلهم في الـمدرسة، وحجم المحفظة عادة يكون بحجم أكثر من الكتب، غالبًا ما تصنع من الجلد، وقد يكون جلدًا طبيعيًا غالي الثمن أو من الجلد الصناعي الرخيص، أو من النايلون أو القماش، أو من",
        category:"أدوات مدرسية",
        image1:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        image2:"https://thumbs.dreamstime.com/b/school-backpack-white-background-151312141.jpg",
        image3:"https://st4.depositphotos.com/10614052/22984/i/1600/depositphotos_229843646-stock-photo-school-backpack-white-background.jpg",
        PriceCuts:200.95,
        testimonialsPrictures:"https://goorelax.shop/wp-content/uploads/2021/06/2-1.jpg",
      },
      {
        id:15,
        title:"هجوم العمالقة حقيبة مدرسية",
        price:109.95,
        description:"لحقيبة المدرسية أو حقيبة الكتب أو الحقيبة الدراسية أو قِمَطْر هي الوسيلة التي يحفظ بها التلاميذ كتبهم وحاجات أخرى (الأدوات المدرسية) عند تنقلهم في الـمدرسة، وحجم المحفظة عادة يكون بحجم أكثر من الكتب، غالبًا ما تصنع من الجلد، وقد يكون جلدًا طبيعيًا غالي الثمن أو من الجلد الصناعي الرخيص، أو من النايلون أو القماش، أو من",
        category:"أدوات مدرسية",
        image1:"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
        image2:"https://thumbs.dreamstime.com/b/school-backpack-white-background-151312141.jpg",
        image3:"https://st4.depositphotos.com/10614052/22984/i/1600/depositphotos_229843646-stock-photo-school-backpack-white-background.jpg",
        PriceCuts:200.95,
        testimonialsPrictures:"https://goorelax.shop/wp-content/uploads/2021/06/2-1.jpg",
      },
      {
      id:2,title:"حقيبة أعمال,قديمة الطراز",price:850.00,PriceCuts:1500.95,
        description:"تُعتبر الحقيبة من المُستلزمات المدرسية الضرورية، حتى تكاد تكون جُزءاً مُهماً من الزي المدرسي، حيثُ لا يستطيع الطالب الذهاب بدونها إلى مدرسته، فهي الوسيلة التي يحمل فيها كتبه المدرسية، وقرطاسيته من الأقلام، والأدوات الهندسية، وتختلف أنواع تلك الحقائب وأشكالها، لكن مهما تعددت، يجب أن تنطبق عليها جميعاً المواصفات الصحية، التي سوف سنذكرها في هذا المقال.   إقرأ المزيد على موضوع.",
        category:"أدوات مدرسية",
        image:"https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1579900877-41aU141yrML.jpg",
        image2:"https://neimanmarcus.scene7.com/is/image/NeimanMarcus/NMN3GCD_20_m?&wid=456&height=570",
        image3:"https://cdn.lookastic.com/brown-leather-backpack/ledge-leather-backpack-61941-original.jpg",
        image4:"https://images.neimanmarcus.com/ca/11/product_assets/N/3/G/C/D/NMN3GCD_au.jpg",
        commentPicture1:"https://goorelax.shop/wp-content/uploads/2021/06/3-1.jpg",
        commentPicture2:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1024x1024.jpg",
        commentPicture3:"https://goorelax.shop/wp-content/uploads/2021/06/WhatsApp-Image-2021-06-16-at-11.41.20-1-1024x1024.jpg",
      }
]